### PR TITLE
added new file "postfix_to_infix"

### PR DESCRIPTION
**Pull request by Sachindrck**
postfix_to_infix.

### CODE REVIEW

**Comment by sahilbansal17** [comment]
@Sachindrck As suggested by @imkaka please indent your code properly.

**Comment by sahilbansal17** [comment]
@Sachindrck Also, you can join the [Hacktoberfest gitter channel](https://gitter.im/Competitive-Coding/Hacktoberfest) for this project for further discussions.

**Comment by Sachindrck** [comment]
Thanks for the Help.

**Comment by Sachindrck** [comment]
okay i will correct it . 
Thanks !  @sahilbansal17 and @imkaka .

**Comment by sahilbansal17** [comment]
@Sachindrck Good job 👍 💯

**Comment by Sachindrck** [comment]
@sahilbansal17  thanks sir!

**Pull request merged**
