### PR TITLE
BellmanFord Algorithm #150 and Forward Spiral of numbers #171 Solved

### PR DESCRIPTION
**Pull request by jstjyoti**
@sahilbansal17  @ramitsawhney27  do review this Bellmanford algorithm .

### CODE REVIEW

**Comment by jstjyoti** [comment]
@sahilbansal17  @ramitsawhney27  @vikasgola  Review Please when you get time

**Comment by jstjyoti** [comment]
#150  Solved using Dynamic Programming BellmanFord Algorithm

**Comment by sahilbansal17** [comment]
@jstjyoti It was earlier also told that don't send PRs from the master branch. Please follow the [guidelines](https://github.com/sahilbansal17/Competitive_Coding/wiki/GSSoC#github-workflow).

**Comment by jstjyoti** [comment]
@sahilbansal17 should I close this PR  and make another from a branch?

**Comment by sahilbansal17** [comment]
Yes.

**Pull request closed without merging**
