### PR TITLE
Weighted Job scheduling

### PR DESCRIPTION
**Pull request by shivhek25**
Solved issue #11

### CODE REVIEW

**Comment by shivhek25** [comment]
@sahilbansal17 Kindly review.

**Comment by sahilbansal17** [comment]
@shivhek25 Please make sure that older commits do not appear in the PR:

- Re fork the repo. (Only this time, since your repo's master branch has these old commits)
- Don't commit changes directly to the master branch.
- Update the master branch before creating a new branch for the PR. Then, push the updates to your github repo.
- Create a new branch and commit the changes in that.
- Now, send a PR. It won't include the older commits.

**Comment by shivhek25** [comment]
@sahilbansal17 What about the other branch I have for cuckoo hashing ? Wont it be affected ?

**Comment by sahilbansal17** [comment]
No, it won't get affected. Please follow the guidelines from next time and don't send PRs from master branch with older commits.

**Pull request closed without merging**
