### PR TITLE
September'19 Lunchtime

### PR DESCRIPTION
**Pull request by riya0522**

### CODE REVIEW

**Comment by riya0522** [comment]
Lunchtime Question 3 added.

**Comment by sahilbansal17** [comment]
@riya0522 Awesome work 👍 
Just can you add spaces in between `=` during assignment statements as described in the [Coding Standards](https://github.com/sahilbansal17/Competitive_Coding/wiki/Coding-Standards).

**Comment by riya0522** [comment]
Hey!
Thanks :)
Sure, will look into it and make the necessary changes.

**Comment by sahilbansal17** [comment]
Thanks @riya0522

**Pull request merged**
