### PR TITLE
Add solution to modified n queens

### PR DESCRIPTION
**Pull request by tanvi15**
PLEASE ignore previous commits. Clearly, I'm still very very new to Git/GitHub. Apologies.
Also, I found this question to be slightly tougher than intermediate, hence took a tad bit longer to upload the solution.

### CODE REVIEW

**Comment by tanvi15** [comment]
@ramitsawhney27 
Firstly, yes. It is n^2 as 'i' is incremented by n in the for loop that runs n*n times. So n of the loop recurs n times.

In the generic n queen problem, the time runs like so - T(n) = O(n^2) + n*T(n-1), which boils down to O(n!) according to big O rules. In the modified problem, the second term becomes n*constant, since there's only a fixed number of blocks that need to be checked, that is, a maximum of 34 blocks (5+5+5+5+4+4+3+3). That in turn, boils down to O(n^2).
I guess the generic n*(n-1)*(n-2)... breaks down to n + (n-1) + (n-2) ....

**Comment by tanvi15** [comment]
@ramitsawhney27 if you were expecting something else, let me know. Don't tell me the answer just yet, I'd like to give it a better shot, if required.

**Comment by ramitsawhney27** [comment]
@tanvi15 nope. This is what I was looking for, great work. I hope you’ve learned something helpful out of this rather than doing the conventional n queens. Will add the points for both the problem and complexity explanation :)

**Comment by tanvi15** [comment]
@ramitsawhney27 yes, this problem was really interesting. Thank you!

**Pull request merged**
