### PR TITLE
Added solution to 71A (#13)

### PR DESCRIPTION
**Pull request by dhairyakhale**
Issue #13 , added solution to Question 71A for tag -strings

### CODE REVIEW

**Comment by sahilbansal17** [comment]
@dhairyakhale There should be an end of line character at the end of *cout* statements which you have missed, otherwise the solution would not pass.

**Comment by dhairyakhale** [comment]
Oh I'm sorry! Looks like I made the edit online and not locally :sweat_smile: I'll do that.

**Comment by sahilbansal17** [comment]
Sure, you can make the edit and commit. It would automatically get added to this pull request.

**Comment by dhairyakhale** [comment]
Made the commit.

**Pull request merged**
