### PR TITLE
deletion.java  program

### PR DESCRIPTION
**Pull request by goelgoel**
Solves #384

### CODE REVIEW

**Comment by sahilbansal17** [comment]
@goelgoel The extension of the file is incorrect. It should not have .docx at the end.

**Comment by goelgoel** [comment]
Sorry for the mistake.I have Reuploaded the file with the correct pattern
now. It does not have the .docx at the end.. Please check it.

**Comment by sahilbansal17** [comment]
Kindly indent the code properly. Also, do add comments.

**Comment by sahilbansal17** [comment]
Remove the docx file, it is still present in the pull request.

**Comment by goelgoel** [comment]
I have committed a new file. please review it.

**Comment by sahilbansal17** [comment]
Yes, it seems fine now 👍

**Comment by sahilbansal17** [comment]
There is compilation error that we get due to the additional curly brace in line 2. Please fix that.

**Comment by goelgoel** [comment]
ok thanks.

**Comment by sahilbansal17** [comment]
> There is compilation error that we get due to the additional curly brace in line 2. Please fix that.

@goelgoel Any update on this?

**Pull request closed without merging**
