### PR TITLE
stack implementation fixed isuue #142

### PR DESCRIPTION
**Pull request by Anujg935**
implemented the stack using arrays and linked lists.

### CODE REVIEW

**Comment by Anujg935** [comment]
plese have a look at both the codes and merge as soon as possible.

**Comment by sahilbansal17** [comment]
@Anujg935 Please delete the other files in this PR and keep only the ones related to the stack implementation.

**Comment by Anujg935** [comment]
I deleted all the other files that are not related to Stack.

**Comment by Anujg935** [comment]
sir, In issue #106 you tagged each STL implementation of stack queue and other data structures as cakewalk but in my issues, you also tagged them as cakewalk but according to me stl implementation is just 10 to 15 lines of code and requires no effort. In my issue #142 I have to code entire data structure from scratch that too with 2 approaches both programs are more than 150 lines of code. So it requires a lot more effort.
If you find so then please revise the tegs otherwise that's okay.

**Comment by sahilbansal17** [comment]
@Anujg935 Currently, there are no files related to stack in this PR, I think you've deleted them also. Please add them.

**Comment by Anujg935** [comment]
Now have a look at stack implementation files i added

**Pull request merged**
