### PR TITLE
Warmup Gssoc and Kruskal's Algorithm #13 #34

### PR DESCRIPTION
**Pull request by Dhiraj240**
Solution of a simple problem for tag-math
https://codeforces.com/problemset/problem/987/B

### CODE REVIEW

**Comment by Dhiraj240** [comment]
I forgot to verify,it failed at test case 5,i think i need to make a function.I will update both this and the issue by tomorrow.

**Comment by sahilbansal17** [comment]
@Dhiraj240 You cannot actually compute powers of such huge numbers, there is some Mathematics involved behind the actual solution since you just need to compare x<sup>y</sup> and y<sup>x</sup>.!

**Comment by Dhiraj240** [comment]
It was a silly mistake of ignoring the condition on input,now its fine.

**Comment by Dhiraj240** [comment]
@sahilbansal17 This pull request was not merged and when i went to give a pull request for kruskal algorithm it got updated here.Is there is a way to do multiple PRs? or something have been done by your side.

**Comment by Dhiraj240** [comment]
@sahilbansal17  This way is fine,also ignore merge pull request #1.

**Comment by ramitsawhney27** [comment]
If you're going to directly pickup a code and modify it, there's a good chance we'll catch it. Just going to close this PR, feel free to take up a new issue.

**Comment by Dhiraj240** [comment]
@sahilbansal17 What all you expect tell me ? Should i change the whole code? If i would have planned to  just change the comment i would have done it much before.

**Pull request closed without merging**
