### PR TITLE
A and B solutions to 510 Div 2 Round

### PR DESCRIPTION
**Pull request by sidsrivatsa**

### CODE REVIEW

**Comment by sidsrivatsa** [comment]
Please wait 7 days before discarding these PRs

**Comment by sahilbansal17** [comment]
@sidsrivatsa Kindly edit your solutions so that they don't use any macros. That would make the code more readable.

**Comment by sahilbansal17** [comment]
@sidsrivatsa You can join the [Hacktoberfest gitter channel](https://gitter.im/Competitive-Coding/Hacktoberfest) for this project for further discussions.

**Comment by sahilbansal17** [comment]
@sidsrivatsa Please remove the macros, otherwise the PR can be discarded.

**Comment by sahilbansal17** [comment]
Thanks @siddhishree

**Pull request closed without merging**
