### PR TITLE
Add problems solutions in Java

### PR DESCRIPTION
**Pull request by AlexandreVelloso**

### CODE REVIEW

**Comment by AlexandreVelloso** [comment]
Solved 4 problems using Java

**Comment by sahilbansal17** [comment]
@AlexandreVelloso Looks awesome, can you just put this files in a folder with your username in [this](https://github.com/sahilbansal17/Competitive_Coding/tree/interview_preparation_kit) branch as you can see I've created a folder with my username.

**Comment by AlexandreVelloso** [comment]
I put the files in the right folder

**Comment by sahilbansal17** [comment]
Good job @AlexandreVelloso 💯

**Pull request merged**
