### PR TITLE
added solution to Problem B.Frog

### PR DESCRIPTION
**Pull request by harshraj22**
Issue #442

### CODE REVIEW

**Comment by harshraj22** [comment]
@sahilbansal17 I didn't understand as where actually you want spaces to be present. Can you point out in the code ?

**Comment by sahilbansal17** [comment]
@harshraj22 In the assignment statements, `a=2` should be written as `a = 2`.

**Comment by harshraj22** [comment]
Updated Accordingly (--amend --no-edit as no other branch depends on this branch ).

**Comment by sahilbansal17** [comment]
Thanks @harshraj22

**Pull request merged**
