### PR TITLE
Hashmap implementation

### PR DESCRIPTION
**Pull request by bscoolcoder**
#58

### CODE REVIEW

**Comment by sahilbansal17** [comment]
@bscoolcoder Please follow [Coding Standards](https://github.com/sahilbansal17/Competitive_Coding/wiki/Coding-Standards) and the file is not having the proper *.cpp* extension. Please add the extension and modify code as per standards.

**Comment by bscoolcoder** [comment]
I have made the changes. Pls review and let me know if some other changes are also required.

**Comment by bscoolcoder** [comment]
Worst case complexity of hashmap insert delete and search is O(1). 
I have added a better explanation for time complexity e explaining best ,worst case . Pls review it and if you want me to implement it with any other method that will give more optimised version, let me know.

**Comment by ramitsawhney27** [comment]
I think you mean the worst case is O(n) as you've commented in the code. The average and best case is O(1). This is actually the amortized complexity. You can just add how the amortized complexity is O(1) in avg and best cases and the PR is good to go.

**Comment by bscoolcoder** [comment]
Sorry, that was a typo(O(1)).
I have commented best case complexity already. Can you pls explain what else do I need to add.( avg case complexity??? )

**Comment by ramitsawhney27** [comment]
Yes. The avg complexity will also be O(1), look up on that. That’s the practical utility of a hashmap. If you’re unsure, lookup amortized complexity for hashing.

**Comment by bscoolcoder** [comment]
Changes done. Please review

**Comment by bscoolcoder** [comment]
Changes done. Please review

**Pull request merged**
