### PR TITLE
Added four new SPOJ problems in C++

### PR DESCRIPTION
**Pull request by shivam-51**

### CODE REVIEW

**Comment by sahilbansal17** [comment]
@shivam-51 Kindly remove macros to make code readable and indent your code as per the [Coding Standards](https://github.com/sahilbansal17/Competitive_Coding/wiki/Coding-Standards)!

**Comment by shivam-51** [comment]
@sahilbansal17 can you check once ? I removed the macros.

**Comment by sahilbansal17** [comment]
@shivam-51 Your code looks improperly indented. Please follow the [Coding Standards](https://github.com/sahilbansal17/Competitive_Coding/wiki/Coding-Standards) and also refer to [Google's C++ Style Guide](https://google.github.io/styleguide/cppguide.html).

**Comment by sahilbansal17** [comment]
Thanks @shivam-51

**Pull request merged**
