### PR TITLE
insertion_sort.cpp

### PR DESCRIPTION
**Pull request by sourabh1031**
@arnav-mandal1234 please review it

### CODE REVIEW

**Comment by sourabh1031** [comment]
@ramitsawhney27  please review it

**Comment by sahilbansal17** [comment]
@sourabh1031 Average case complexity is missing.

**Comment by sourabh1031** [comment]
@sahilbansal17  i have already written for average case please see the last line best case para but if you still want to edit i am sending another commit within 10 min

**Comment by sourabh1031** [comment]
@sahilbansal17  @ramitsawhney27 please review now

**Comment by sahilbansal17** [comment]
@sourabh1031 Please provide an explanation why it is *O(n<sup>2</sup>)* in the avg case.

**Comment by sourabh1031** [comment]
@sahilbansal17 done

**Pull request merged**
