### PR TITLE
Added binary_tree.cpp

### PR DESCRIPTION
**Pull request by sourabh1031**

### CODE REVIEW

**Comment by sourabh1031** [comment]
@sahilbansal17 i have added insertion and deletion , and  height till now and rest of two i will submit by tommorow

**Comment by sourabh1031** [comment]
@sahilbansal17  please review it

**Comment by sourabh1031** [comment]
@sahilbansal17 truth to say for deletion operation in binary tree and continuous and foldable binary tree i have taken reference from geeksforgeeks

**Comment by sahilbansal17** [comment]
@sourabh1031 Taking reference is not a problem, but the way code is written is very similar, so I suggest you to write it without referring to the code given and only with whatever you understood.

**Comment by sourabh1031** [comment]
@sahilbansal17 Please check morris traversal

**Comment by sourabh1031** [comment]
@vikasgola @ramitsawhney27 please review it

**Comment by sourabh1031** [comment]
@vikasgola actually i looked for another algorithms for thisi but i can't find the algorithm and .you are right so i am closing up the issue

**Pull request closed without merging**
