### PR TITLE
Create ANGGRA.cpp

### PR DESCRIPTION
**Pull request by vichitr**

### CODE REVIEW

**Comment by sahilbansal17** [comment]
@vichitr Awesome, if you could remove the template so that code is more readable, that would be great!

**Comment by vichitr** [comment]
Most of the things have been used. Doesn't make sense if remove them.

**Comment by sahilbansal17** [comment]
@vichitr You can rewrite the code to not use the template, if possible.

**Comment by sahilbansal17** [comment]
Thanks @vichitr

**Pull request closed without merging**
