### PR TITLE
Fixed issue #95 Tower Of hanoi

### PR DESCRIPTION
**Pull request by Anujg935**
done the coding of tower of Hanoi iteratively

### CODE REVIEW

**Comment by vikasgola** [comment]
@Anujg935 
Please don't send Pull-request from the master branch.
You can read [Github-flow](https://gist.github.com/Chaser324/ce0505fbed06b947d962)

**Comment by Anujg935** [comment]
Yes I know that points will be allotted only after completion of whole issue .it's just that I am doing these in different files so I thought to commit it and the modified solution is also about to complete

**Comment by Anujg935** [comment]
I just commit it so that if this has any doubt then you can give me comments about that

**Comment by Anujg935** [comment]
Now have a look at the tower of Hanoi modified code and everything of this issue is fixed. If there is anything to add then please tell me, Otherwise please review and merge it.

**Pull request merged**
